### ISSUE TITLE
Getting error while on build command 

### ISSUE THREAD

**Issue by nasbasarin** [blockwatch-cc/tzindex#52] opened 2024-01-03 09:37 UTC
i am getting the following error while trying make build command

build
go clean
build .: cannot find module for path .
make: *** [Makefile:20: build] Error 1

is there anything i missed?

**Comment by echa** [comment] 2024-01-03 09:48
Did you run `make build` on master branch or an older version? It works on master for me. 

This kind of error message appears when go build cannot find `.go` files in the current directory. The makefile specifies `./cmd/...` as source which means all programs in sub-directories are built at once.

**Comment by nasbasarin** [comment] 2024-01-03 09:54
yes . tried on master branch.

**Comment by echa** [comment] 2024-01-03 10:03
Does `go build ./cmd/...` throw the same error? If yes, maybe your Go version is too old or you made an unintentional change to go.mod? Worked for me with Go 1.20.5

**Comment by nasbasarin** [comment] 2024-01-03 10:06
> go build ./cmd/...

go version go1.13.8 linux/amd64
go build ./cmd/... returns the following 

go: downloading github.com/echa/config v1.0.9
go: downloading blockwatch.cc/tzgo v1.17.4
go: downloading github.com/daviddengcn/go-colortext v1.0.0
go: downloading blockwatch.cc/tzpro-go v0.17.5
go: downloading go.etcd.io/bbolt v1.3.8
go: downloading blockwatch.cc/packdb v0.0.0-20231228074625-5e8e6458d7be
go: downloading github.com/echa/log v1.2.4
go: downloading github.com/cespare/xxhash v1.1.0
go: downloading github.com/qri-io/jsonschema v0.2.1
go: extracting github.com/cespare/xxhash v1.1.0
go: downloading github.com/awesome-gocui/gocui v1.1.0
go: extracting go.etcd.io/bbolt v1.3.8
go: downloading github.com/fatih/color v1.16.0
go: extracting github.com/fatih/color v1.16.0
go: downloading golang.org/x/sys v0.15.0
go: extracting github.com/echa/config v1.0.9
go: extracting github.com/daviddengcn/go-colortext v1.0.0
go: extracting github.com/qri-io/jsonschema v0.2.1
go: extracting github.com/echa/log v1.2.4
go: downloading github.com/mattn/go-colorable v0.1.13
go: extracting golang.org/x/sys v0.15.0
go: downloading github.com/gorilla/mux v1.8.1
go: extracting github.com/awesome-gocui/gocui v1.1.0
go: downloading github.com/qri-io/jsonpointer v0.1.1
go: downloading github.com/gdamore/tcell/v2 v2.7.0
go: extracting blockwatch.cc/tzpro-go v0.17.5
go: downloading github.com/echa/code v1.0.1
go: extracting blockwatch.cc/packdb v0.0.0-20231228074625-5e8e6458d7be
go: downloading github.com/echa/goprocinfo v0.0.0-20210921162345-49464edb7812
go: downloading github.com/mattn/go-isatty v0.0.20
go: extracting github.com/mattn/go-isatty v0.0.20
go: extracting github.com/qri-io/jsonpointer v0.1.1
go: extracting github.com/mattn/go-colorable v0.1.13
go: extracting github.com/gorilla/mux v1.8.1
go: downloading github.com/mattn/go-runewidth v0.0.15
go: downloading github.com/hashicorp/golang-lru v1.0.2
go: downloading github.com/tidwall/gjson v1.17.0
go: extracting github.com/gdamore/tcell/v2 v2.7.0
go: extracting github.com/mattn/go-runewidth v0.0.15
go: downloading github.com/rivo/uniseg v0.4.4
go: extracting blockwatch.cc/tzgo v1.17.4
go: extracting github.com/hashicorp/golang-lru v1.0.2
go: downloading github.com/echa/bson v0.0.0-20220430141917-c0fbdf7f8b79
go: extracting github.com/tidwall/gjson v1.17.0
go: downloading github.com/pierrec/lz4 v2.6.1+incompatible
go: downloading golang.org/x/text v0.14.0
go: downloading github.com/tidwall/pretty v1.2.1
go: downloading github.com/tidwall/match v1.1.1
go: extracting github.com/rivo/uniseg v0.4.4
go: downloading github.com/ericlagergren/decimal v0.0.0-20221120152707-495c53812d05
go: extracting github.com/echa/code v1.0.1
go: extracting github.com/tidwall/pretty v1.2.1
go: downloading github.com/klauspost/compress v1.17.4
go: downloading golang.org/x/crypto v0.17.0
go: extracting github.com/tidwall/match v1.1.1
go: downloading golang.org/x/net v0.19.0
go: downloading golang.org/x/exp v0.0.0-20231226003508-02704c960a9b
go: extracting github.com/echa/bson v0.0.0-20220430141917-c0fbdf7f8b79
go: downloading github.com/decred/dcrd/dcrec/secp256k1/v4 v4.2.0
go: extracting github.com/echa/goprocinfo v0.0.0-20210921162345-49464edb7812
go: downloading golang.org/x/term v0.15.0
go: extracting github.com/ericlagergren/decimal v0.0.0-20221120152707-495c53812d05
go: extracting golang.org/x/term v0.15.0
go: downloading github.com/acarl005/stripansi v0.0.0-20180116102854-5a71ef0e047d
go: extracting github.com/acarl005/stripansi v0.0.0-20180116102854-5a71ef0e047d
go: extracting golang.org/x/exp v0.0.0-20231226003508-02704c960a9b
go: extracting github.com/decred/dcrd/dcrec/secp256k1/v4 v4.2.0
go: downloading github.com/gdamore/encoding v1.0.0
go: extracting golang.org/x/crypto v0.17.0
go: extracting golang.org/x/net v0.19.0
go: downloading github.com/gorilla/schema v1.2.1
go: downloading github.com/lucasb-eyer/go-colorful v1.2.0
go: extracting github.com/gdamore/encoding v1.0.0
go: extracting github.com/gorilla/schema v1.2.1
go: extracting golang.org/x/text v0.14.0
go: extracting github.com/lucasb-eyer/go-colorful v1.2.0
go: extracting github.com/klauspost/compress v1.17.4
go: extracting github.com/pierrec/lz4 v2.6.1+incompatible
go: finding blockwatch.cc/tzgo v1.17.4
go: finding blockwatch.cc/tzpro-go v0.17.5
go: finding blockwatch.cc/packdb v0.0.0-20231228074625-5e8e6458d7be
go: finding github.com/daviddengcn/go-colortext v1.0.0
go: finding github.com/echa/config v1.0.9
go: finding github.com/echa/log v1.2.4
go: finding github.com/acarl005/stripansi v0.0.0-20180116102854-5a71ef0e047d
go: finding github.com/qri-io/jsonschema v0.2.1
go: finding github.com/awesome-gocui/gocui v1.1.0
go: finding github.com/fatih/color v1.16.0
go: finding github.com/echa/code v1.0.1
go: finding github.com/decred/dcrd/dcrec/secp256k1/v4 v4.2.0
go: finding github.com/cespare/xxhash v1.1.0
go: finding go.etcd.io/bbolt v1.3.8
go: finding github.com/mattn/go-colorable v0.1.13
go: finding golang.org/x/crypto v0.17.0
go: finding golang.org/x/sys v0.15.0
go: finding golang.org/x/exp v0.0.0-20231226003508-02704c960a9b
go: finding github.com/mattn/go-isatty v0.0.20
go: finding github.com/ericlagergren/decimal v0.0.0-20221120152707-495c53812d05
go: finding github.com/klauspost/compress v1.17.4
go: finding github.com/echa/bson v0.0.0-20220430141917-c0fbdf7f8b79
go: finding github.com/pierrec/lz4 v2.6.1+incompatible
go: finding github.com/hashicorp/golang-lru v1.0.2
go: finding github.com/gorilla/mux v1.8.1
go: finding github.com/echa/goprocinfo v0.0.0-20210921162345-49464edb7812
go: finding github.com/qri-io/jsonpointer v0.1.1
go: finding github.com/gdamore/tcell/v2 v2.7.0
go: finding github.com/gorilla/schema v1.2.1
go: finding github.com/mattn/go-runewidth v0.0.15
go: finding golang.org/x/net v0.19.0
go: finding github.com/rivo/uniseg v0.4.4
go: finding github.com/tidwall/gjson v1.17.0
go: finding golang.org/x/text v0.14.0
go: finding github.com/tidwall/match v1.1.1
go: finding github.com/tidwall/pretty v1.2.1
build blockwatch.cc/tzindex/cmd/tzindex: cannot load io/fs: malformed module path "io/fs": missing dot in first path element

**Comment by nasbasarin** [comment] 2024-01-03 13:00
i have upgraded go version and run
build
go clean
CGO_ENABLED=0 go build -mod=mod -a -o ./ -ldflags "-w -X blockwatch.cc/tzindex/main.version=v17.0.1-2-g7a77572-alpine -X blockwatch.cc/tzindex/main.gitcommit=7a77572" ./cmd/...

now when i try to use tzindex command  it is saying command not found error.

**Comment by echa** [comment] 2024-01-03 13:07
Its probably not in your `$PATH`. The makefile build puts the executable into the current directory, so try run it with `./tzindex`.

**Comment by nasbasarin** [comment] 2024-01-03 14:30
ok.
i think it is giving correct response . don't know why tzstats is not working .
https://github.com/blockwatch-cc/tzstats-legacy
![Screenshot from 2024-01-03 19-59-37](https://github.com/blockwatch-cc/tzindex/assets/99649379/ec3cc56d-1121-4488-995e-f946220cf681)

**Comment by echa** [comment] 2024-01-03 15:44
Its due to the following issues:

- run tzindex with `-enable-cors` to include the required CORS headers for the browser
- run tzindex with `-full` to index all data

The open-source version of TzStats is quite old and there are likely several breaking changes in API responses so that not all explorer pages are working anymore.

**Comment by nasbasarin** [comment] 2024-01-03 16:01
i have tried with both still getting same error

**Comment by echa** [comment] 2024-01-03 16:40
I fixed an issue with default CORS headers. This should make it work. Please pull from master branch again and rebuild.

**Comment by nasbasarin** [comment] 2024-01-03 16:49
> I fixed an issue with default CORS headers. This should make it work. Please pull from master branch again and rebuild.

Thank you . with the help of this cors issue is resolved.
i am seeing tezos indexer stalled in explorer . is this an issue?
![Screenshot from 2024-01-03 22-17-26](https://github.com/blockwatch-cc/tzindex/assets/99649379/40c46a14-5d4a-4e72-b71c-3b400e4bc385)

**Comment by echa** [comment] 2024-01-03 16:53
Is this a sandbox network? Try and bake a few blocks.

**Comment by nasbasarin** [comment] 2024-01-04 04:29
yes this is a sandbox network.
i tried to bake few more blocks but most of the time it says tezos indexer stalled or offline

**Comment by echa** [comment] 2024-01-04 06:05
This is both expected behavior.

- to get around the stalled state you could use Flextesa which would bake sandbox blocks automatically, see https://github.com/blockwatch-cc/tzindex/blob/master/etl/crawler.go#L248-L274
- by default tzindex indexes head~1 to prevent issues with reorgs, you can set `-crawler.delay=0` to always index at head block

**Comment by nasbasarin** [comment] 2024-01-04 09:29
what is actually happening at tzindexer stalled time?

**Comment by echa** [comment] 2024-01-04 09:49
The indexer waits for the next block (using RPC `/monitor/heads/main`) and then processes the next block which is at `head - crawler.delay`. If no new block arrives for one minute, the status will flip to `stalled` meaning the node is likely cut off from the network, too slow to validate blocks or the network did not produce a new block yet.

**Comment by nasbasarin** [comment] 2024-01-04 10:06
what tzindexer offline is showing most of the time. also there is nothing showing in cycle.

**Comment by echa** [comment] 2024-01-04 10:11
Need more detail. Send responses from `/explorer/status`, `/explorer/tip`, `/explorer/config/head`.

**Comment by echa** [comment] 2024-01-04 15:15
Looks like different issues. The chain the indexer crawls had its last block on Dec 26, 2023. For this reason `/explorer/status` reports `stalled` state. The `offline` message in the browser is displayed by the frontend when the browser's Internet connection is offline. It has nothing to with the indexer.

**Comment by nasbasarin** [comment] 2024-01-04 16:32
The time stamp showing is also incorrect. i just baked two blocks today but it is showing the node created date.

**Comment by nasbasarin** [comment] 2024-01-09 10:44
I am not getting live blocks in explorer . need to restart indexer each time when i baked a block to get it on explorer.

**Comment by nasbasarin** [comment] 2024-01-15 17:17
> This is both expected behavior.
> 
> * to get around the stalled state you could use Flextesa which would bake sandbox blocks automatically, see https://github.com/blockwatch-cc/tzindex/blob/master/etl/crawler.go#L248-L274
> * by default tzindex indexes head~1 to prevent issues with reorgs, you can set `-crawler.delay=0` to always index at head block

i din't get how i can use flextesa from the link is there any other document that can help me with this?

thanks in advance : )

**Comment by echa** [comment] 2024-01-15 17:45
Hi, Flextesa https://gitlab.com/tezos/flextesa is a Docker-based system that helps manage Tezos sandboxes. We have been using it for a while to test in development, but unfortunately it is no longer actively maintained. The most recent Docker image only has Oxford 1 support, their Oxford 2 support is in the dev branch (you probably need to build it on your own). 

Here is a small script to run a Flextesa sandbox:

```bash
#!/bin/sh
set -eo pipefail

TEZOS_IMAGE=oxheadalpha/flextesa:latest
TEZOS_PROTO=oxford

CMD=${1}
case "$CMD" in
    start )
      # daemon mode
      echo "Starting sandbox..."
      docker run --rm \
        --name tezos_sandbox \
        -d \
        -p 127.0.0.1:8732:20000 \
        -e block_time=1 \
        ${TEZOS_IMAGE} \
        ${TEZOS_PROTO}box start
      echo "Done"
      ;;
    stop )
      echo "Stopping sandbox..."
      docker stop tezos_sandbox
      echo "Done"
      ;;
    logs )
      docker logs -f tezos_sandbox
      ;;
    * )
      echo "Unknown command $CMD"
      exit 1
      ;;
esac
```

Then point tzindex to `-rpc.url localhost:8732`.

**Comment by nasbasarin** [comment] 2024-01-15 17:55
I am running my tezos sandbox node using scripts i created. is there anyway i can use the flextesa making update in my script?or do i need to use the docker version. also will it support other protocols like nairobi?

**Comment by echa** [comment] 2024-01-15 17:59
Yes, you have to use Docker. Flextesa has its own system to manage sandbox parameters and for starting up the node etc. All runs inside a Docker container. There are lots of config options, but I haven't had the need to use them. It supports Nairobi too, use `nairobibox start` as docker command.

**Comment by nasbasarin** [comment] 2024-01-16 13:47
> Here is a small script to run a Flextesa sandbox:
> 
> ```shell
> #!/bin/sh
> set -eo pipefail
> 
> TEZOS_IMAGE=oxheadalpha/flextesa:latest
> TEZOS_PROTO=oxford
> 
> CMD=${1}
> case "$CMD" in
>     start )
>       # daemon mode
>       echo "Starting sandbox..."
>       docker run --rm \
>         --name tezos_sandbox \
>         -d \
>         -p 127.0.0.1:8732:20000 \
>         -e block_time=1 \
>         ${TEZOS_IMAGE} \
>         ${TEZOS_PROTO}box start
>       echo "Done"
>       ;;
>     stop )
>       echo "Stopping sandbox..."
>       docker stop tezos_sandbox
>       echo "Done"
>       ;;
>     logs )
>       docker logs -f tezos_sandbox
>       ;;
>     * )
>       echo "Unknown command $CMD"
>       exit 1
>       ;;
> esac
> ```
> 
this script is giving unknown command error

**Comment by nasbasarin** [comment] 2024-01-17 06:40
The timestand showing in tzexplorer is wrong . do you know why it is happending?

**Comment by echa** [comment] 2024-01-17 12:11
This error here is due to the Tezos sandbox configuration and the way Tezos assigns snapshot indexes. The cycle is too short (8 blocks) but the protocol still assigns snapshot index 15 to the last snapshot in the cycle. 

Will be fixed in the upcoming Oxford release which is in preparation.

Also, I'm closing this issue because it has gone way out of topic. Please open new issues if needed or join our Discord chat.

**Closed as completed by echa** 2024-01-17 12:11 UTC
