### ISSUE TITLE
Multiple errors parsing operation on v6.0.2

### ISSUE THREAD

**Issue by xplat** [blockwatch-cc/tzindex#26] opened 2020-04-30 21:44 UTC
On dockerhub v6.0.2:

```bash
curl http://OUR-INTERNAL-SERVER/explorer/op/ooHe73NX3PS9vu3PsYeGRaUd5RbSGy3GmdqGnPFiYaad9VJMqPm
```

```json
{
  "errors": [
    {
      "code": 1003,
      "status": 500,
      "message": "internal server error",
      "scope": "ReadOp",
      "detail": "cannot marshal response",
      "reason": "json: error calling MarshalJSON for type *micheline.BigMapValue: micheline: type mismatch val_type=prim[Unit] type_code=list / type={\"annots\":[\"%disburse\"],\"args\":[{\"prim\":\"address\"}],\"prim\":\"list\"} -- value={\"prim\":\"Unit\"} / map=map[string]interface {}{}"
    }
  ]
}
```

logs:

```
2020/04/30 21:37:16 ERRO MICH Rendering prim type bytes as address: invalid binary address length 34
2020/04/30 21:37:16 ERRO MICH RENDER ERROR
typ={"annots":["%disburse"],"args":[{"prim":"address"}],"prim":"list"}
val={"prim":"Unit"}
err=micheline: type mismatch val_type=prim[Unit] type_code=list / type={"annots":["%disburse"],"args":[{"prim":"address"}],"prim":"list"} -- value={"prim":"Unit"} / map=map[string]interface {}{}
2020/04/30 21:37:16 ERRO SRVR BW-7c1cdf59267ef57392f6ce856f879728f5f222a6 Error sending response: json: error calling MarshalJSON for type *micheline.BigMapValue: micheline: type mismatch val_type=prim[Unit] type_code=list / type={"annots":["%disburse"],"args":[{"prim":"address"}],"prim":"list"} -- value={"prim":"Unit"} / map=map[string]interface {}{} in struct server.ExplorerOpList{(*server.ExplorerOp)(0xc0001f0780), (*server.ExplorerOp)(0xc0001f0960)}
```

It's possible this is a partial duplicate of #25 but I'm pretty sure at least the first line of logs ("invalid binary address") is not.  That part seems to be caused by the use of entrypoint-suffixed addresses which are a valid but rarely-used part of the protocol.

(It's also quite possible the rest of it is not a duplicate of #25 either ... it looks similar but when I tried to replicate #25 using an `/op/` call it didn't seem to work.)

**Comment by echa** [comment] 2020-05-03 16:50
The address length issue is fixed. The second is a duplicate of #25. Will be fixed in the next release, but may take a week or two to land here due to higher priority projects.

**Comment by smithy9901** [comment] 2020-10-17 20:48
Can't you make the tag 6.0.3-fix pls?

**Comment by echa** [comment] 2021-03-12 08:34
Closing this old issue. The problem should have been solved by v7/v8. We no longer fail returning any operations where storage data unwrapping fails. Instead the unwrapped storage contains an embedded error object plus the original type + value primitive trees.

**Closed by echa** 2021-03-12 08:34 UTC
