### ISSUE TITLE
balance 0 is smaller than outgoing amount 374 on ithacanet

### ISSUE THREAD

**Issue by glehmann** [blockwatch-cc/tzindex#41] opened 2022-04-08 12:53 UTC
when running tzindex on ithacanet, the following error is raised:
~~~
2022/04/08 12:41:50.882666 ERRO BLOC Processing block 312914 BMbfdJAZYPj9s1XJ6fA8LdHKjHPytkFjJJqQQz1bqg5xK7Rij8z: build stage 4: acc.update id 147589 tz2UPSgvCW2keRj8fF3SzCdYzJZHzVAsX5DS balance 0 is smaller than outgoing amount 374
2022/04/08 12:41:50.882985 INFO BLOC Stopping blockchain sync due to too many errors at 312913.
2022/04/08 12:41:51.831792 INFO BLOC Exiting monitor loop on cancel.
2022/04/08 12:41:51.832694 INFO BLOC Stopping blockchain ingest on cancel.
~~~
This is with tzindex on master.

**Comment by echa** [comment] 2022-04-08 13:26
Strange, just tried with master and can't reproduce. Can you share the node URL and command line.

**Comment by glehmann** [comment] 2022-04-08 14:18
Indexation was done on https://rpc.ithacanet.connect.eniblock.fr , that I've configured yesterday with tezos 12.3.0. Once I had the error, I restarted tzindex with https://rpc.ithaca.tzstats.com in order to check if the error was related to our node, but still get the same error.

**Comment by echa** [comment] 2022-04-08 15:13
I'm confirming with both nodes, but it'll take a while over the Internet. One thing that comes to mind: did you start indexing with an older version and continue with master branch later on? I specifically mean this bugfix

* a639d8d | Fix counting block bonus (8 days ago)

**Comment by echa** [comment] 2022-04-08 15:56
Yes please re-run from scratch. Sorry for the inconvenience!

**Comment by glehmann** [comment] 2022-04-08 23:54
I've re-run the indexation from scratch with the same result, unfortunately.

**Comment by echa** [comment] 2022-04-09 09:53
So the problem is the configuration of your node. There is a breaking change in v12.1+ that strips large metadata from transactions under the default setting. See here:

- https://rpc.ithacanet.connect.eniblock.fr/chains/main/blocks/312197 (search for `"metadata": "too large"`)

This is not an indexer error, but a node configuration error. You need to restart your node with `--metadata-size-limit unlimited`. Unfortunately you also need to resync your node from scratch to reconstruct the missing transaction metadata. This applies to ALL test networks and mainnet where you have ever run v12.1, v12.2 or v12.3 (!!).

By a lucky accident `rpc.ithaca.tzstats.com` is not impacted as we run an unversioned Octez node at Git commit 22d5dd489a654977f89aed4d450d1a35d4ce9e15 between v12.0 and v12.1. Our version does neither have the metadata limit nor a second (but unrelated) metadata read bug that got introduced in v12.1 and v12.2. This explains why the error did not show up in my tests against our archive node.

I'm closing this issue, feel free to reopen if additional problems arise.

**Closed by echa** 2022-04-09 09:53 UTC

**Comment by glehmann** [comment] 2022-04-10 12:02
I restarted a new tezos node with `--metada-size-limit=unlimited` and rerun the indexation with the last version on master, but still get an error, though much more explicit this time:

```
2022/04/10 03:36:31.032900 INFO BLOC Processed 82 blocks in 10.14s (3530 transactions, height 312185, 2022-03-30 18:01:20 +0000 UTC, q=0, t=1.55794ms, s=syncing)
2022/04/10 03:36:32.385497 ERRO BLOC Processing block 312197 BMU4uXz1QXM5X5G45nCEatMQSvkAkBjSxXYxcfgcio3PTcGTsLr: build stage 2: metadata too large! Your archive node has pruned metadata and must be rebuilt. Always run Octez v12.x with --metadata-size-limit unlimited. Sorry for your trouble.
```

https://rpc.ithacanet.connect.eniblock.fr/chains/main/blocks/312197 still has `"metadata":"too large"` in it, so I'm wondering if the problem I have may come from the snapshot I've used to initialize the node, because the metadata were already stripped from the node used to create the snapshot. I'll try to setup my tezos nodes without using a snapshot to see if it helps.

Running tzindex (and I guess any indexer) has become much more difficult recently :-(

**Comment by glehmann** [comment] 2022-04-11 15:00
It worked without initializing the node with a snapshot :-)

Thanks a lot for your help!
